linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - emptyFallthrough
      - paramTypeCombine
      - unnamedResult
      - exitAfterDefer
    settings:
      rangeValCopy:
        sizeThreshold: 32
  funlen:
    lines: 150
    statements: 120
  gocognit:
    min-complexity: 35
linters:
  enable-all: true
  disable:
    - maligned
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - goconst
    - interfacer
    - wsl
    - godot
    - gofumpt
    - nlreturn
    - exhaustivestruct
    - cyclop
    - exhaustruct
    - nosnakecase
    - nonamedreturns
  fast: false
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "`noCopy` is unused"
    - 'Magic number: 1\D '
    - 'Magic number: 2\D '
    - 'Magic number: 64\D '
    - 'commentFormatting: put a space between'
    - "Function 'registerMetrics' is too long"
    - "type assertion must be checked"
    - "metric name should not include type"
    - "counter metrics should have"
    - "variable name 'l' is too short"
    - "parameter name 'c' is too short"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
