language: generic
dist: bionic
os: linux
services:
  - docker
addons:
  apt:
    packages:
    - apache2-dev
    - make
    - gcc
go:
  - "1.14"

install:
  - make

script:
  -  make test

notifications:
  email:
    - sven@nierlein.de
