{
 "title": "Apache Local Copy",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Server",
    "query": "label_values(apache_server_info, instance)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(apache_requests_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(apache_requests_total, status)"
   },
   {
    "name": "vhost",
    "label": "VHost",
    "query": "label_values(apache_requests_total, vhost)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apache_requests_total{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apache_requests_total{instance=~\"$host\",method=~\"$method\",status=~\"(4|5)..\", vhost=~\"$vhost\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apache_response_time_seconds_sum{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n/\nsum(rate(apache_response_time_seconds_count{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n",
     "legendFormat": "Average Response Time"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apache_workers{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apache_process_counter{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apache_cpu_load{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Server List",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "apache_server_info{instance=~\"$host\"}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests/sec by vhost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(vhost)(rate(apache_requests_total{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_requests_total{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_requests_total{instance=~\"$host\",status=~\"(4|5)..\", vhost=~\"$vhost\"}[1m]))",
     "legendFormat": "Errors per second"
    }
   ]
  },
  {
   "title": "Worker Scoreboard ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "apache_workers_scoreboard{instance=~\"$host\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpu_load{instance=~\"$host\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Avg. Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_response_time_seconds_sum{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n/\nsum(rate(apache_response_time_seconds_count{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Avg. Response Size ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_response_size_bytes_sum{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n/\nsum(rate(apache_response_size_bytes_count{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "Request Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/sec By Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(method, status)(rate(apache_requests_total{instance=~\"$host\", status=~\"$status\", vhost=~\"$vhost\"}[1m]))",
       "legendFormat": "{{method}} Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average Response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(method, status)(rate(apache_response_time_seconds_sum{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n/\nsum by(method, status)(rate(apache_response_time_seconds_count{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))\n",
       "legendFormat": "{{method}} Status: {{status}}"
      }
     ]
    },
    {
     "title": "Response Size By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(method, status)(rate(apache_response_size_bytes_sum{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))/sum by(method, status)(rate(apache_response_size_bytes_count{instance=~\"$host\", status=~\"$status\", method=~\"$method\", vhost=~\"$vhost\"}[1m]))",
       "legendFormat": "{{method}} Status: {{status}}"
      }
     ]
    },
    {
     "title": "Response Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum by (le)(rate(apache_response_time_seconds_bucket{instance=~\"$host\", method=~\"$method\", status=~\"$status\", vhost=~\"$vhost\"}[1m]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Size Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum by (le)(rate(apache_response_size_bytes_bucket{instance=~\"$host\", method=~\"$method\", status=~\"$status\", vhost=~\"$vhost\"}[1m]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apache_process_total_threads{instance=~\"$host\"})",
       "legendFormat": "Processes"
      },
      {
       "expr": "sum(apache_process_counter{instance=~\"$host\"})",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(apache_process_total_rss_memory_bytes{instance=~\"$host\"})",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum(apache_process_total_virt_memory_bytes{instance=~\"$host\"})",
       "legendFormat": "VMS"
      }
     ]
    },
    {
     "title": "Total Disk IO",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apache_process_total_io_read_bytes{instance=~\"$host\"}[1m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(apache_process_total_io_write_bytes{instance=~\"$host\"}[1m]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Avg. Memory per Process",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(apache_process_total_rss_memory_bytes{instance=~\"$host\"})\n/\nsum(apache_process_counter{instance=~\"$host\"})",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum(apache_process_total_virt_memory_bytes{instance=~\"$host\"})\n/\nsum(apache_process_counter{instance=~\"$host\"})",
       "legendFormat": "VMS"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apache_process_total_open_fd{instance=~\"$host\"})\n/\nsum(apache_process_counter{instance=~\"$host\"})",
       "legendFormat": "Open Files By Process"
      },
      {
       "expr": "sum(apache_process_total_open_fd{instance=~\"$host\"})",
       "legendFormat": "Total Open Files"
      }
     ]
    }
   ]
  }
 ]
}