---
- hosts: all
  tasks:

# machine preparation
  - yum:
      name:
        - perl-Test-Harness
        - httpd-devel
        - gcc
        - rsync
        - gdb
        - strace
        - inotify-tools
        - centos-release-scl
      state: present
  - yum:
      name:
        - devtoolset-3-gcc
      state: present

# apache site
  - shell: omd config demo set APACHE_MODE own
  - shell: omd config demo set APACHE_TCP_ADDR '0.0.0.0'
  - shell: omd config demo set CORE none
  - shell: omd config demo set CRONTAB off
  - shell: omd config demo set PNP4NAGIOS off
  - shell: omd config demo set THRUK_COOKIE_AUTH off
  - shell: omd config demo set DEFAULT_GUI none
  - name: Remove apache authentication
    file:
      path: /opt/omd/sites/demo/etc/apache/conf.d/auth.conf
      state: absent
  - name: enable module in apache
    file:
      src: /src/t/testbox/apache/apache.conf
      dest: /omd/sites/demo/etc/apache/conf.d/prom.conf
      owner: demo
      group: demo
      state: link
  - shell: sudo su - demo -c "/src/t/testbox/apache/build.sh"
  - name: enable build watcher
    file:
      src: /src/t/testbox/apache/build_watcher.init
      dest: /omd/sites/demo/etc/init.d/build_watcher
      owner: demo
      group: demo
      state: link
  - name: enable build watcher
    file:
      src: ../init.d/build_watcher
      dest: /omd/sites/demo/etc/rc.d/10-build_watcher
      owner: demo
      group: demo
      state: link
  - shell: sudo su - demo -c "rm -f etc/init-hooks.d/apache-*"

# create dashboard site
  - shell: omd create dashboard
  - shell: omd config dashboard set APACHE_MODE own
  - shell: omd config dashboard set APACHE_TCP_ADDR '0.0.0.0'
  - shell: omd config dashboard set CORE none
  - shell: omd config dashboard set CRONTAB off
  - shell: omd config dashboard set PNP4NAGIOS off
  - shell: omd config dashboard set THRUK_COOKIE_AUTH off
  - shell: omd config dashboard set DEFAULT_GUI grafana
  - shell: omd config dashboard set PROMETHEUS on
  - shell: omd config dashboard set GRAFANA on
  - name: Remove apache authentication
    file:
      path: /opt/omd/sites/dashboard/etc/apache/conf.d/auth.conf
      state: absent
  - shell: sudo su - dashboard -c "rm -f etc/init-hooks.d/apache-*"
  - name: enable prometheus config
    file:
      src: /src/t/testbox/apache/prometheus.yml
      dest: /omd/sites/dashboard/etc/prometheus/prometheus.d/scrape_configs/static/01-apache.yml
      owner: dashboard
      group: dashboard
      state: link
  - name: set default user for grafana
    lineinfile:
      path: /omd/sites/dashboard/etc/apache/conf.d/grafana.conf
      regexp: 'RequestHeader set X-WEBAUTH-USER "omdadmin"'
      insertbefore: 'RequestHeader unset Authorization'
      line: 'RequestHeader set X-WEBAUTH-USER "omdadmin"'
  - shell: omd start dashboard
