name: citest
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install apache2-dev make gcc
    - run: make clean
    - run: make
    - run: make clean
    - run: make build
    - run: make clean
    - run: make updatedeps
      if: github.event_name != 'pull_request'
    - run: make citest
